/**
 * MCP Remote Installer Router
 *
 * Provides endpoints for downloading the MCP remote agent installer.
 * This allows remote machines to connect to the VOW MCP task server.
 *
 * Endpoints:
 * - GET /api/mcp-installer/install.sh - Download installer script
 * - GET /api/mcp-installer/config - Get current server configuration
 * - GET /api/mcp-installer/quick-install - One-liner quick install script
 */

import { Hono } from 'hono';
import { z } from 'zod';
import { getSettings } from '../config.js';
import { getLogger } from '../utils/logger.js';

const logger = getLogger('mcp-installer');

// MCP Server configuration (loaded from environment or settings)
const MCP_SERVER_HOST = process.env['MCP_SERVER_HOST'] || '192.168.2.126';
const MCP_SERVER_PORT = process.env['MCP_SERVER_PORT'] || '3456';
const MCP_SERVER_TOKEN = process.env['MCP_SERVER_TOKEN'] || '';

/**
 * Response schema for configuration endpoint.
 */
export const mcpConfigResponseSchema = z.object({
  serverUrl: z.string(),
  serverHost: z.string(),
  serverPort: z.string(),
  hasToken: z.boolean(),
  downloadUrl: z.string(),
  quickInstallCommand: z.string(),
});

export type McpConfigResponse = z.infer<typeof mcpConfigResponseSchema>;

/**
 * Generate the main installer script content.
 */
function generateInstallerScript(serverUrl: string): string {
  return `#!/bin/bash
# =============================================================================
# VOW MCP Remote Agent Installer
# =============================================================================
# Generated by VOW Backend
# Server URL: ${serverUrl}
# =============================================================================

set -e

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
BLUE='\\033[0;34m'
NC='\\033[0m'

# Default values
INSTALL_DIR="\$HOME/vow-mcp-agent"
SERVER_URL=""
AUTH_TOKEN=""
AGENT_NAME="\$(hostname)-agent"
AGENT_ROLE="developer"
MACHINE_ID=""

# Parse command line arguments
while [[ \$# -gt 0 ]]; do
  case \$1 in
    --server-url) SERVER_URL="\$2"; shift 2 ;;
    --token) AUTH_TOKEN="\$2"; shift 2 ;;
    --name) AGENT_NAME="\$2"; shift 2 ;;
    --role) AGENT_ROLE="\$2"; shift 2 ;;
    --install-dir) INSTALL_DIR="\$2"; shift 2 ;;
    --machine-id) MACHINE_ID="\$2"; shift 2 ;;
    -h|--help)
      echo "VOW MCP Remote Agent Installer"
      echo ""
      echo "Usage: \$0 [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --server-url URL   Central task server URL (required)"
      echo "  --token TOKEN      Authentication token (required)"
      echo "  --name NAME        Agent display name (default: hostname-agent)"
      echo "  --role ROLE        Agent role: manager, developer, reviewer, tester,"
      echo "                     documenter, analyst, architect, devops, general"
      echo "  --install-dir DIR  Installation directory (default: ~/vow-mcp-agent)"
      echo "  --machine-id ID    Machine identifier (auto-generated if not set)"
      exit 0
      ;;
    *) echo -e "\${RED}Unknown option: \$1\${NC}"; exit 1 ;;
  esac
done

echo -e "\${BLUE}"
echo "============================================================"
echo "  VOW MCP Remote Agent Installer"
echo "============================================================"
echo -e "\${NC}"

# Validate required arguments
if [ -z "\$SERVER_URL" ]; then
  echo -e "\${RED}Error: --server-url is required\${NC}"
  echo "Example: \$0 --server-url http://192.168.2.126:3456 --token YOUR_TOKEN"
  exit 1
fi

if [ -z "\$AUTH_TOKEN" ]; then
  echo -e "\${RED}Error: --token is required\${NC}"
  exit 1
fi

# Generate machine ID if not provided
if [ -z "\$MACHINE_ID" ]; then
  MACHINE_ID="remote-\$(hostname | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g')-\$(date +%s | tail -c 5)"
fi

echo -e "\${GREEN}Configuration:\${NC}"
echo "  Server URL:   \$SERVER_URL"
echo "  Agent Name:   \$AGENT_NAME"
echo "  Agent Role:   \$AGENT_ROLE"
echo "  Machine ID:   \$MACHINE_ID"
echo "  Install Dir:  \$INSTALL_DIR"
echo ""

# Check prerequisites
echo -e "\${YELLOW}Checking prerequisites...\${NC}"

if ! command -v node &> /dev/null; then
  echo -e "\${RED}Error: Node.js is not installed\${NC}"
  exit 1
fi

NODE_VERSION=\$(node -v | sed 's/v//' | cut -d. -f1)
if [ "\$NODE_VERSION" -lt 18 ]; then
  echo -e "\${RED}Error: Node.js 18+ required (found v\$NODE_VERSION)\${NC}"
  exit 1
fi
echo -e "  \${GREEN}✓\${NC} Node.js \$(node -v)"

if ! command -v npm &> /dev/null; then
  echo -e "\${RED}Error: npm is not installed\${NC}"
  exit 1
fi
echo -e "  \${GREEN}✓\${NC} npm \$(npm -v)"

# Test server connectivity
echo ""
echo -e "\${YELLOW}Testing connection to task server...\${NC}"
HEALTH_RESPONSE=\$(curl -s -o /dev/null -w "%{http_code}" "\$SERVER_URL/health" 2>/dev/null || echo "000")

if [ "\$HEALTH_RESPONSE" = "200" ]; then
  echo -e "  \${GREEN}✓\${NC} Server is reachable"
else
  echo -e "\${RED}Error: Cannot connect to server at \$SERVER_URL\${NC}"
  exit 1
fi

# Test authentication
echo -e "\${YELLOW}Testing authentication...\${NC}"
AUTH_RESPONSE=\$(curl -s -o /dev/null -w "%{http_code}" \\
  -H "Authorization: Bearer \$AUTH_TOKEN" \\
  "\$SERVER_URL/agents" 2>/dev/null || echo "000")

if [ "\$AUTH_RESPONSE" = "200" ]; then
  echo -e "  \${GREEN}✓\${NC} Authentication successful"
else
  echo -e "\${RED}Error: Authentication failed\${NC}"
  exit 1
fi

# Create installation directory
mkdir -p "\$INSTALL_DIR"
cd "\$INSTALL_DIR"

# Create package.json
echo -e "\${YELLOW}Initializing Node.js project...\${NC}"
cat > package.json << 'PKG_EOF'
{
  "name": "vow-mcp-agent",
  "version": "1.0.0",
  "type": "module",
  "main": "build/mcp-bridge.js",
  "scripts": { "build": "tsc", "start": "node build/mcp-bridge.js" },
  "dependencies": { "@modelcontextprotocol/sdk": "^1.0.0", "uuid": "^11.0.0" },
  "devDependencies": { "@types/node": "^22.0.0", "@types/uuid": "^10.0.0", "typescript": "^5.7.0" }
}
PKG_EOF

cat > tsconfig.json << 'TSC_EOF'
{
  "compilerOptions": {
    "target": "ES2022", "module": "NodeNext", "moduleResolution": "NodeNext",
    "esModuleInterop": true, "strict": true, "outDir": "./build",
    "rootDir": "./src", "declaration": true, "skipLibCheck": true
  },
  "include": ["src/**/*"]
}
TSC_EOF

mkdir -p src

# Create MCP bridge source
cat > src/mcp-bridge.ts << 'BRIDGE_EOF'
#!/usr/bin/env node
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CallToolRequestSchema, ListToolsRequestSchema, ListResourcesRequestSchema, ReadResourceRequestSchema } from "@modelcontextprotocol/sdk/types.js";
import { v4 as uuidv4 } from "uuid";

const SERVER_URL = process.env.TASK_SERVER_URL || "http://localhost:3456";
const AUTH_TOKEN = process.env.TASK_SERVER_TOKEN || "";
const AGENT_NAME = process.env.AGENT_NAME || "Remote Agent";
const AGENT_ROLE = process.env.AGENT_ROLE || "developer";
const MACHINE_ID = process.env.MACHINE_ID || \\\`remote-\\\${uuidv4().slice(0, 8)}\\\`;

let registeredAgentId: string | null = null;

async function apiCall<T>(method: string, path: string, body?: unknown): Promise<{ success: boolean; data?: T; error?: string }> {
  try {
    const response = await fetch(\\\`\\\${SERVER_URL}\\\${path}\\\`, {
      method,
      headers: { "Content-Type": "application/json", Authorization: \\\`Bearer \\\${AUTH_TOKEN}\\\`, ...(registeredAgentId ? { "X-Agent-ID": registeredAgentId } : {}) },
      body: body ? JSON.stringify(body) : undefined,
    });
    return await response.json() as { success: boolean; data?: T; error?: string };
  } catch (error) {
    return { success: false, error: error instanceof Error ? error.message : "Unknown error" };
  }
}

const server = new Server({ name: "vow-remote-agent", version: "1.0.0" }, { capabilities: { tools: {}, resources: {} } });

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    { name: "register_agent", description: "Register with VOW task server", inputSchema: { type: "object", properties: { name: { type: "string" }, role: { type: "string" }, capabilities: { type: "array", items: { type: "string" } } }, required: ["name", "role"] } },
    { name: "heartbeat", description: "Send heartbeat", inputSchema: { type: "object", properties: { status: { type: "string" } } } },
    { name: "list_agents", description: "List all agents", inputSchema: { type: "object", properties: {} } },
    { name: "create_task", description: "Create a task", inputSchema: { type: "object", properties: { title: { type: "string" }, description: { type: "string" }, priority: { type: "string" }, tags: { type: "array", items: { type: "string" } }, assign_to: { type: "string" } }, required: ["title", "description"] } },
    { name: "list_tasks", description: "List tasks", inputSchema: { type: "object", properties: { status: { type: "string" }, assigned_to: { type: "string" } } } },
    { name: "get_my_tasks", description: "Get my tasks", inputSchema: { type: "object", properties: {} } },
    { name: "claim_task", description: "Claim a task", inputSchema: { type: "object", properties: { task_id: { type: "string" } }, required: ["task_id"] } },
    { name: "submit_result", description: "Submit task result", inputSchema: { type: "object", properties: { task_id: { type: "string" }, result: { type: "string" }, success: { type: "boolean" } }, required: ["task_id", "result", "success"] } },
    { name: "dashboard", description: "Get dashboard stats", inputSchema: { type: "object", properties: {} } },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;
  const fmt = (r: { success: boolean; data?: unknown; error?: string }) => ({ content: [{ type: "text" as const, text: JSON.stringify(r.success ? r.data : { error: r.error }, null, 2) }] });
  switch (name) {
    case "register_agent": {
      const { name: n, role, capabilities = [] } = args as { name: string; role: string; capabilities?: string[] };
      const r = await apiCall<{ agentId: string }>("POST", "/agents/register", { name: n, role, capabilities, machineId: MACHINE_ID });
      if (r.success && r.data) { registeredAgentId = r.data.agentId; return fmt({ success: true, data: { agentId: registeredAgentId, serverUrl: SERVER_URL } }); }
      return fmt(r);
    }
    case "heartbeat": { if (!registeredAgentId) return fmt({ success: false, error: "Not registered" }); return fmt(await apiCall("POST", \\\`/agents/\\\${registeredAgentId}/heartbeat\\\`, { status: (args as { status?: string })?.status || "idle" })); }
    case "list_agents": return fmt(await apiCall("GET", "/agents"));
    case "create_task": { const { title, description, priority, tags, assign_to } = args as { title: string; description: string; priority?: string; tags?: string[]; assign_to?: string }; return fmt(await apiCall("POST", "/tasks", { title, description, priority, tags, assignTo: assign_to })); }
    case "list_tasks": { const { status, assigned_to } = (args as { status?: string; assigned_to?: string }) || {}; const p = new URLSearchParams(); if (status) p.set("status", status); if (assigned_to) p.set("assignedTo", assigned_to); return fmt(await apiCall("GET", \\\`/tasks\\\${p.toString() ? \\\`?\\\${p}\\\` : ""}\\\`)); }
    case "get_my_tasks": if (!registeredAgentId) return fmt({ success: false, error: "Not registered" }); return fmt(await apiCall("GET", \\\`/tasks?assignedTo=\\\${registeredAgentId}\\\`));
    case "claim_task": { if (!registeredAgentId) return fmt({ success: false, error: "Not registered" }); return fmt(await apiCall("POST", \\\`/tasks/\\\${(args as { task_id: string }).task_id}/claim\\\`)); }
    case "submit_result": { const { task_id, result, success } = args as { task_id: string; result: string; success: boolean }; return fmt(await apiCall("POST", \\\`/tasks/\\\${task_id}/submit\\\`, { result, success })); }
    case "dashboard": return fmt(await apiCall("GET", "/dashboard"));
    default: return fmt({ success: false, error: \\\`Unknown tool: \\\${name}\\\` });
  }
});

server.setRequestHandler(ListResourcesRequestSchema, async () => ({ resources: [{ uri: "vow://config", mimeType: "application/json", name: "Configuration" }] }));
server.setRequestHandler(ReadResourceRequestSchema, async (req) => {
  if (req.params.uri === "vow://config") return { contents: [{ uri: "vow://config", mimeType: "application/json", text: JSON.stringify({ serverUrl: SERVER_URL, agentId: registeredAgentId, name: AGENT_NAME, role: AGENT_ROLE, machineId: MACHINE_ID }, null, 2) }] };
  throw new Error(\\\`Resource not found: \\\${req.params.uri}\\\`);
});

async function main() {
  if (AUTH_TOKEN && AGENT_NAME) {
    console.error(\\\`Auto-registering: \\\${AGENT_NAME} (\\\${AGENT_ROLE})\\\`);
    const r = await apiCall<{ agentId: string }>("POST", "/agents/register", { name: AGENT_NAME, role: AGENT_ROLE, capabilities: [], machineId: MACHINE_ID });
    if (r.success && r.data) { registeredAgentId = r.data.agentId; console.error(\\\`Registered: \\\${registeredAgentId}\\\`); }
  }
  await server.connect(new StdioServerTransport());
  console.error("VOW MCP Agent running");
}

main().catch((e) => { console.error("Fatal:", e); process.exit(1); });
BRIDGE_EOF

echo -e "  \${GREEN}✓\${NC} Source files created"

npm install --quiet
echo -e "\${YELLOW}Building TypeScript...\${NC}"
npm run build
echo -e "  \${GREEN}✓\${NC} Build complete"

# Create MCP configuration for Claude Code
MCP_CONFIG_DIR="\$HOME/.claude"
mkdir -p "\$MCP_CONFIG_DIR"
MCP_CONFIG_FILE="\$MCP_CONFIG_DIR/mcp.json"

cat > "\$MCP_CONFIG_FILE" << MCP_EOF
{
  "mcpServers": {
    "vow-agent": {
      "command": "node",
      "args": ["\$INSTALL_DIR/build/mcp-bridge.js"],
      "env": {
        "TASK_SERVER_URL": "\$SERVER_URL",
        "TASK_SERVER_TOKEN": "\$AUTH_TOKEN",
        "AGENT_NAME": "\$AGENT_NAME",
        "AGENT_ROLE": "\$AGENT_ROLE",
        "MACHINE_ID": "\$MACHINE_ID"
      }
    }
  }
}
MCP_EOF

echo -e "  \${GREEN}✓\${NC} MCP config: \$MCP_CONFIG_FILE"

# Create convenience scripts
cat > "\$INSTALL_DIR/check-status.sh" << 'STATUS_EOF'
#!/bin/bash
source "\$INSTALL_DIR/.env" 2>/dev/null || true
echo "VOW Task Server Status"
curl -s -H "Authorization: Bearer \$TASK_SERVER_TOKEN" "\$TASK_SERVER_URL/dashboard" | jq '.data' 2>/dev/null || echo "Failed"
STATUS_EOF
chmod +x "\$INSTALL_DIR/check-status.sh"

cat > "\$INSTALL_DIR/.env" << ENV_EOF
TASK_SERVER_URL=\$SERVER_URL
TASK_SERVER_TOKEN=\$AUTH_TOKEN
AGENT_NAME=\$AGENT_NAME
AGENT_ROLE=\$AGENT_ROLE
MACHINE_ID=\$MACHINE_ID
ENV_EOF

echo ""
echo -e "\${GREEN}============================================================\${NC}"
echo -e "\${GREEN}  Installation Complete!\${NC}"
echo -e "\${GREEN}============================================================\${NC}"
echo ""
echo "Run 'claude' to start using the VOW MCP agent tools."
echo ""
`;
}

/**
 * Generate quick install one-liner script.
 */
function generateQuickInstallScript(installerUrl: string): string {
  return `#!/bin/bash
# VOW MCP Quick Installer
# Usage: curl -sSL ${installerUrl} | bash -s -- --server-url URL --token TOKEN

set -e
TEMP_DIR=$(mktemp -d)
cd "$TEMP_DIR"
curl -sSL -o install.sh "${installerUrl.replace('/quick-install', '/install.sh')}"
chmod +x install.sh
./install.sh "$@"
cd /
rm -rf "$TEMP_DIR"
`;
}

/**
 * Create the MCP installer router.
 */
export function createMcpInstallerRouter(): Hono {
  const router = new Hono();

  /**
   * GET /api/mcp-installer/config
   *
   * Returns configuration info for the MCP server.
   */
  router.get('/config', (c) => {
    const settings = getSettings();
    const baseUrl = `http://${MCP_SERVER_HOST}:${settings.port || 3001}`;
    const serverUrl = `http://${MCP_SERVER_HOST}:${MCP_SERVER_PORT}`;

    const response: McpConfigResponse = {
      serverUrl,
      serverHost: MCP_SERVER_HOST,
      serverPort: MCP_SERVER_PORT,
      hasToken: Boolean(MCP_SERVER_TOKEN),
      downloadUrl: `${baseUrl}/api/mcp-installer/install.sh`,
      quickInstallCommand: `curl -sSL ${baseUrl}/api/mcp-installer/quick-install | bash -s -- --server-url ${serverUrl} --token YOUR_TOKEN`,
    };

    logger.info('MCP installer config requested', { host: c.req.header('host') });
    return c.json(response);
  });

  /**
   * GET /api/mcp-installer/install.sh
   *
   * Returns the main installer script.
   */
  router.get('/install.sh', (c) => {
    const serverUrl = `http://${MCP_SERVER_HOST}:${MCP_SERVER_PORT}`;
    const script = generateInstallerScript(serverUrl);

    logger.info('MCP installer script downloaded', { host: c.req.header('host') });

    c.header('Content-Type', 'text/plain; charset=utf-8');
    c.header('Content-Disposition', 'attachment; filename="install.sh"');
    return c.text(script);
  });

  /**
   * GET /api/mcp-installer/quick-install
   *
   * Returns a one-liner quick install script.
   */
  router.get('/quick-install', (c) => {
    const settings = getSettings();
    const baseUrl = `http://${MCP_SERVER_HOST}:${settings.port || 3001}`;
    const script = generateQuickInstallScript(`${baseUrl}/api/mcp-installer`);

    logger.info('MCP quick installer requested', { host: c.req.header('host') });

    c.header('Content-Type', 'text/plain; charset=utf-8');
    return c.text(script);
  });

  /**
   * GET /api/mcp-installer/token
   *
   * Returns the server token (protected - requires admin auth).
   * This endpoint should only be used in development or by authenticated admins.
   */
  router.get('/token', (c) => {
    // In production, this should require authentication
    if (!MCP_SERVER_TOKEN) {
      return c.json({ error: 'Token not configured' }, 404);
    }

    return c.json({
      token: MCP_SERVER_TOKEN,
      serverUrl: `http://${MCP_SERVER_HOST}:${MCP_SERVER_PORT}`,
      warning: 'Keep this token secure. Do not share publicly.',
    });
  });

  return router;
}

// Export default router instance
export const mcpInstallerRouter = createMcpInstallerRouter();
